version: '3.0'
services:
  backend:
    container_name: backend-service
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
  frontend:
    container_name: frontend-service
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge

